name: Rancher VXLAN Holder Mode
description: |
  Rancher Networking plugin using VXLAN overlay.
version: v0.2.0
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,kubernetes'
