name: Rancher VXLAN HostNS Mode
description: |
  Rancher Networking plugin using VXLAN overlay.
version: v0.1.0
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,kubernetes'
